import { Link } from "react-router-dom";

import type { AlertsView, RunsView, SystemView } from "@stocks-agent/dashboard-contracts";
import type { ResourceState } from "../../api/useDashboardResource";
import { AsyncView } from "../../components/AsyncView";
import { SafeTelegramPreview } from "../../components/SafeTelegramPreview";

const statusLabel = (value: string) => value.replaceAll("_", " ");

function RunReceipts({ data, fallback }: { data: RunsView; fallback: SystemView["latest_by_kind"] }) {
  return <section className="nested-section"><h3>Runs and write receipts</h3>{data.runs.length > 0 ? <div className="card-grid">{data.runs.map((run) => <article className="card" key={run.id}><p className="card-kicker">{run.kind}</p><h3><Link to={`/runs/${run.id}`}>{run.status}</Link></h3><p>{run.evaluation_count} evaluations · {run.suggestion_count} suggestions · publication {run.publication_status ?? "none"}</p><details className="run-receipt-details"><summary>Full run receipt</summary><dl className="receipt-meta"><div><dt>Started</dt><dd>{new Date(run.started_at).toLocaleString()}</dd></div><div><dt>Finished</dt><dd>{run.finished_at ? new Date(run.finished_at).toLocaleString() : "not finished"}</dd></div><div><dt>Data as of</dt><dd>{run.data_as_of ? new Date(run.data_as_of).toLocaleString() : "unavailable"}</dd></div><div><dt>Policy</dt><dd>{run.policy_version === null ? "unavailable" : `Policy ${run.policy_version}`}</dd></div></dl></details></article>)}</div> : Object.keys(fallback).length === 0 ? <p className="empty-copy">No run receipt summary is available.</p> : <ul>{Object.entries(fallback).map(([kind, run]) => <li key={kind}>{kind}: {run?.status ?? "missing"}</li>)}</ul>}</section>;
}

function AlertReceipts({ data }: { data: AlertsView }) {
  return <section className="nested-section"><h3>Alert and send receipts</h3>{data.alerts.length > 0 ? <div className="card-grid">{data.alerts.map((alert) => <article className="card" key={alert.id}><p className="card-kicker">{alert.kind} · {alert.phase}</p><h3>{statusLabel(alert.state)}</h3><p>{alert.attempt_count} send attempt{alert.attempt_count === 1 ? "" : "s"} · Telegram message IDs {alert.telegram_message_ids.length > 0 ? alert.telegram_message_ids.join(", ") : "none"}</p>{alert.suppression_reason && <p>Suppression: {alert.suppression_reason}</p>}<details className="alert-receipt-details"><summary>Full alert receipt</summary><SafeTelegramPreview text={alert.rendered_text} links={alert.sources} /><dl className="receipt-meta"><div><dt>Hash</dt><dd>{alert.rendered_hash}</dd></div><div><dt>Template</dt><dd>Template {alert.template_version}</dd></div><div><dt>Created</dt><dd>{alert.created_at ? new Date(alert.created_at).toLocaleString() : "unavailable"}</dd></div><div><dt>Delivered</dt><dd>{alert.delivered_at ? new Date(alert.delivered_at).toLocaleString() : "not delivered"}</dd></div><div><dt>Rule / event / action</dt><dd>{[alert.rule_ticker, alert.rule_state, alert.event_status, alert.owner_action].filter(Boolean).join(" · ") || "not linked"}</dd></div></dl></details></article>)}</div> : <p className="empty-copy">No alert receipts are available.</p>}</section>;
}

export function SystemPage({ data, runs, alerts, runsState, alertsState }: { data: SystemView; runs?: RunsView; alerts?: AlertsView; runsState?: ResourceState<RunsView>; alertsState?: ResourceState<AlertsView> }) {
  const resolvedRuns = runs ?? (runsState?.status === "ready" ? runsState.envelope.data : null);
  const resolvedAlerts = alerts ?? (alertsState?.status === "ready" ? alertsState.envelope.data : null);
  const runItems = resolvedRuns?.runs ?? Object.values(data.latest_by_kind).filter((run): run is NonNullable<typeof run> => Boolean(run));
  const alertItems = resolvedAlerts?.alerts ?? [];
  const latestRun = [...runItems].sort((left, right) => Date.parse(right.started_at) - Date.parse(left.started_at))[0] ?? null;
  const orderedAlerts = [...alertItems].sort((left, right) => Date.parse(right.created_at) - Date.parse(left.created_at));
  const latestAlert = orderedAlerts[0] ?? null;
  const latestTelegram = orderedAlerts.find((alert) => alert.telegram_message_ids.length > 0)?.telegram_message_ids[0] ?? null;
  return (
    <div className="page-stack">
      <header className="page-heading"><p className="eyebrow">Advanced audit</p><h1>Receipts</h1><p>A concise status summary with the complete run, alert, and policy record available below.</p></header>
      <section className="metric-grid system-summary"><div><span>Last run</span><strong>{latestRun ? statusLabel(latestRun.status) : "Unavailable"}</strong><small>{latestRun?.kind ?? "No run receipt"}</small></div><div><span>Latest alert</span><strong>{latestAlert ? statusLabel(latestAlert.state) : statusLabel(data.latest_publication_status ?? "unavailable")}</strong><small>{latestAlert ? `${latestAlert.kind} · ${latestAlert.phase}` : "Publication receipt"}</small></div><div><span>Latest Telegram</span><strong>{latestTelegram ?? "None"}</strong><small>{latestTelegram ? "Persisted message ID" : "No message receipt"}</small></div><div><span>Alert mode</span><strong>{data.alert_mode}</strong><small>Suggestion delivery mode</small></div></section>
      <section className="section-block"><h2>Permanent boundaries</h2><ul className="boundary-list"><li>Owner only</li><li>Suggestion only</li><li>Friend invitations disabled</li><li>Brokerage authority none</li></ul></section>
      <details className="section-block disclosure-block system-receipts"><summary><h2>Run and alert receipts</h2></summary><div className="disclosure-content">{runsState ? <AsyncView state={runsState}>{(value) => <RunReceipts data={value} fallback={data.latest_by_kind} />}</AsyncView> : <RunReceipts data={runs ?? { runs: [] }} fallback={data.latest_by_kind} />}{alertsState ? <AsyncView state={alertsState}>{(value) => <AlertReceipts data={value} />}</AsyncView> : <AlertReceipts data={alerts ?? { alerts: [] }} />}</div></details>
      <details className="section-block disclosure-block system-diagnostics"><summary><h2>Write, send, and deploy boundaries</h2></summary><div className="disclosure-content"><section><h3>Versions and latest records</h3><dl className="receipt-meta"><div><dt>Product</dt><dd>{data.product_version}</dd></div><div><dt>API</dt><dd>{data.api_version}</dd></div><div><dt>Policy receipt</dt><dd>{data.policy_version ?? "unavailable"}</dd></div><div><dt>Intelligence run</dt><dd>{data.latest_intelligence_run_id ?? "unavailable"}</dd></div><div><dt>Latest publication</dt><dd>{data.latest_publication_status ? statusLabel(data.latest_publication_status) : "unavailable"}</dd></div><div><dt>Latest report</dt><dd>{data.latest_report?.title ?? "unavailable"}</dd></div></dl></section><section className="nested-section"><h3>Source collection status</h3>{data.source_coverage.length === 0 ? <p className="empty-copy">No bounded source coverage receipt is available.</p> : <ul>{data.source_coverage.map((source) => <li key={source.provider}>{source.provider}: {source.status}; {source.accepted_count} accepted, {source.dropped_count} dropped</li>)}</ul>}</section><section className="nested-section"><h3>Authority boundaries</h3><ul><li>No browser write route or financial mutation authority.</li><li>Send status is reported only from persisted publication receipts.</li><li>Deployment status is unavailable in this read model; this page makes no deployment claim.</li></ul></section></div></details>
    </div>
  );
}
