#!/usr/bin/env python3
"""Validate the reviewed NYSE calendar and generate bounded Edge-runtime copies."""
from __future__ import annotations

import argparse
from datetime import date
import hashlib
import json
from pathlib import Path
from typing import Mapping

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "config" / "nyse_calendar.json"
TARGETS = (
    ROOT / "supabase/functions/market-briefing-gateway/_shared/nyse-calendar.generated.ts",
    ROOT / "supabase/functions/owner-dashboard-api/nyse-calendar.generated.ts",
)


def canonical_json(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"), sort_keys=True)


def _iso_day(value: object, *, year: int) -> str:
    if not isinstance(value, str):
        raise ValueError("calendar dates must be strings")
    try:
        parsed = date.fromisoformat(value)
    except ValueError as exc:
        raise ValueError("calendar dates must be real ISO dates") from exc
    if parsed.isoformat() != value or parsed.year != year:
        raise ValueError("calendar dates must be canonical and inside their year")
    return value


def validate_calendar(document: object) -> dict[str, object]:
    if not isinstance(document, Mapping) or set(document) != {
        "version", "exchange", "timezone", "coverage", "source", "years",
    }:
        raise ValueError("calendar must contain exactly the reviewed keys")
    if document["version"] != 1 or document["exchange"] != "NYSE" \
            or document["timezone"] != "America/New_York":
        raise ValueError("calendar identity is unsupported")
    coverage = document["coverage"]
    source = document["source"]
    years = document["years"]
    if not isinstance(coverage, Mapping) or set(coverage) != {"start_year", "end_year"} \
            or coverage != {"start_year": 2026, "end_year": 2028}:
        raise ValueError("calendar coverage must be exactly 2026 through 2028")
    if not isinstance(source, Mapping) or set(source) != {"url", "reviewed_at"} \
            or source["url"] != "https://www.nyse.com/trade/hours-calendars":
        raise ValueError("calendar source must be the reviewed NYSE schedule")
    _iso_day(source.get("reviewed_at"), year=2026)
    expected_years = [str(value) for value in range(2026, 2029)]
    if not isinstance(years, Mapping) or list(years) != expected_years:
        raise ValueError("calendar years must be ordered and contiguous")
    normalized_years: dict[str, object] = {}
    for year_text in expected_years:
        year = int(year_text)
        row = years[year_text]
        if not isinstance(row, Mapping) or set(row) != {"full_day_closures", "early_closes"}:
            raise ValueError("calendar year has unexpected keys")
        closures = row["full_day_closures"]
        early = row["early_closes"]
        if not isinstance(closures, list) or not isinstance(early, list):
            raise ValueError("calendar sessions must be arrays")
        checked_closures = [_iso_day(value, year=year) for value in closures]
        if checked_closures != sorted(set(checked_closures)):
            raise ValueError("calendar closures must be sorted and unique")
        checked_early: list[dict[str, str]] = []
        for value in early:
            if not isinstance(value, Mapping) or set(value) != {"date", "local_time"} \
                    or value["local_time"] != "13:00":
                raise ValueError("calendar early close must be an exact 13:00 session")
            checked_early.append({
                "date": _iso_day(value["date"], year=year),
                "local_time": "13:00",
            })
        early_days = [value["date"] for value in checked_early]
        if early_days != sorted(set(early_days)):
            raise ValueError("calendar early closes must be sorted and unique")
        if set(checked_closures) & set(early_days):
            raise ValueError("calendar closures and early closes must be disjoint")
        normalized_years[year_text] = {
            "full_day_closures": checked_closures,
            "early_closes": checked_early,
        }
    return {
        "version": 1,
        "exchange": "NYSE",
        "timezone": "America/New_York",
        "coverage": dict(coverage),
        "source": dict(source),
        "years": normalized_years,
    }


def load_calendar(path: Path = SOURCE) -> dict[str, object]:
    try:
        return validate_calendar(json.loads(path.read_text()))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError("reviewed NYSE calendar is unreadable") from exc


def render_typescript(document: Mapping[str, object]) -> str:
    canonical = canonical_json(document)
    digest = hashlib.sha256(canonical.encode()).hexdigest()
    pretty = json.dumps(document, ensure_ascii=False, indent=2, sort_keys=True)
    return (
        "// Generated by scripts/sync_market_calendar.py; do not edit.\n"
        f"export const NYSE_CALENDAR_SOURCE_SHA256 = \"{digest}\" as const;\n"
        f"export const NYSE_CALENDAR = {pretty} as const;\n"
    )


def sync(*, source: Path = SOURCE, targets: tuple[Path, ...] = TARGETS, check: bool = False) -> bool:
    rendered = render_typescript(load_calendar(source))
    drifted = [target for target in targets if not target.is_file() or target.read_text() != rendered]
    if check:
        return not drifted
    for target in targets:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return 0 if sync(check=args.check) else 1


if __name__ == "__main__":
    raise SystemExit(main())
